apiVersion: apps/v1
kind: Deployment
metadata:
    name: rtgc-server
    labels:
      app: rtgc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtgc-server
  template:
    metadata:
      labels:
        app: rtgc-server
    spec:
      containers:
        - name: rtgc-server
          image: nndergunov/rtgc:server
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: server-configuration
---
apiVersion: v1
kind: Service
metadata:
  name: rtgcserver-service
spec:
  type: NodePort
  selector:
    app: rtgc-server
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080